version: "3.9"

services:
  web:
    image: odoo:16.0
    depends_on:
      - db
    ports:
      - 8069:8069
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./extra-addons:/mnt/extra-addons
    env_file:
      - env/odoo.env
    command: --
  db:
    image: postgres:14
    ports:
      - 5432:5432
    env_file:
      - env/postgresql.env
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    restart: on-failure

volumes:
  odoo-web-data:
  odoo-db-data:
